# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class Characters(BaseModel):
    name: typing.Optional[str] = None
    role: typing.Optional[str] = None
    relationships: typing.List["Relationship"]

class Relationship(BaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    weight: typing.Optional[types.Weight] = None

class TextSections(BaseModel):
    section_id: typing.Optional[str] = None
    text: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
