# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class Fighter(BaseModel):
    name: typing.Optional[str] = None
    hp: typing.Optional[int] = None
    max_hp: typing.Optional[int] = None
    inventory: typing.List["InventoryItem"]

class GameState(BaseModel):
    player: typing.Optional["Fighter"] = None
    opponent: typing.Optional["Fighter"] = None
    last_player_move: typing.Optional[str] = None

class InventoryItem(BaseModel):
    name: typing.Optional[str] = None
    quantity: typing.Optional[int] = None
    effect_value: typing.Optional[int] = None

class OpponentTurn(BaseModel):
    action: typing.Optional[types.ActionType] = None
    shout: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
