# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Fighter": types.Fighter,
    "stream_types.Fighter": stream_types.Fighter,

    "types.GameState": types.GameState,
    "stream_types.GameState": stream_types.GameState,

    "types.InventoryItem": types.InventoryItem,
    "stream_types.InventoryItem": stream_types.InventoryItem,

    "types.OpponentTurn": types.OpponentTurn,
    "stream_types.OpponentTurn": stream_types.OpponentTurn,


    "types.ActionType": types.ActionType,

}