# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Characters": types.Characters,
    "stream_types.Characters": stream_types.Characters,

    "types.Relationship": types.Relationship,
    "stream_types.Relationship": stream_types.Relationship,

    "types.TextSections": types.TextSections,
    "stream_types.TextSections": stream_types.TextSections,


    "types.Weight": types.Weight,

}