# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.LitCharacterization": types.LitCharacterization,
    "stream_types.LitCharacterization": stream_types.LitCharacterization,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.Subtask": types.Subtask,
    "stream_types.Subtask": stream_types.Subtask,

    "types.Ticket": types.Ticket,
    "stream_types.Ticket": stream_types.Ticket,


    "types.Priority": types.Priority,

}